#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 22 04:42:14 2020

@author: ext-liekhussc_c
"""

    if XAS:
        DIR = "/sf/alvra/data/p17983/raw/scan_data/" + scan_name + "/"
    if XES:
        DIR = "/sf/alvra/data/p17983/raw/" + scan_name + "/"
    DIR_json = "/sf/alvra/data/p17983/res/scan_info/"


os.path.basename(filename)